# Generated by Django 4.2.7 on 2026-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('mtl_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('texture_file', models.ImageField(blank=True, null=True, upload_to='textures/')),
                ('roughness_map', models.ImageField(blank=True, null=True, upload_to='textures/')),
                ('metalness_map', models.ImageField(blank=True, null=True, upload_to='textures/')),
                ('alpha_map', models.ImageField(blank=True, null=True, upload_to='textures/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('model3d', 'Model 3D')], editable=False, max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
    ]
