# Generated by Django 4.2.7 on 2026-02-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_album_media_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='album',
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, help_text='Nazwa dla albumu lub opcjonalny opis', max_length=200),
        ),
        migrations.AddField(
            model_name='media',
            name='parent_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portfolio.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('model3d', 'Model 3D'), ('album', 'Album')], default='image', max_length=10),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
