# Generated by Django 4.2.7 on 2026-02-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_media_album_media_name_media_parent_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
